require "open-uri"
require "stringio"

module Credits
  module_function

  GITHUB_REPOS = {
    "cilium/cilium" => "LICENSE",
    "metallb/metallb" => "LICENSE",
    "moritzheiber/laptop-provisioning" => "LICENSE.md",
    "ruby/ruby-infra-recipe" => "https://www.ruby-lang.org/en/about/license.txt",
  }

  def extract_from_github
    s = StringIO.new("")
    s.write("CREDITS generated by  [./script/credits.rb](./script/credits.rb); DO NOT EDIT.\n\n")
    GITHUB_REPOS.each do |repo, file|
      url = if file.start_with?("https://") || file.start_with?("http://")
              file
            else
              "https://raw.githubusercontent.com/#{repo}/master/#{file}"
            end
      puts "recv from #{file}"
      s.write("## #{repo}\n\n")
      open(url) { |remote| s.write "```\n#{remote.read}\n```" }
      s.write("\n\n")
    end
    s.rewind
    open("CREDITS.md", "w+b") { |local| local.write(s.read) }
    s.close
  end
end

Credits.extract_from_github
